[bell]
color = "#ffffff"

[font.bold]
family = "Monoid Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Monoid Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Monoid Nerd Font"
style = "Italic"

[font.normal]
family = "Monoid Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001B[72;5u"
key = "H"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[74;5u"
key = "J"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[75;5u"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[76;5u"
key = "L"
mods = "Control|Shift"

[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 0.9
