[opener]
pdf_open = [
	{ run = 'zathura "$@"', orphan = true},
]

play = [
	{ run = 'vlc "$@"', orphan = true, for = "unix" },
]

[open]
prepend_rules = [
	{ name = "*.pdf", use = "pdf_open" },
	{ mime = "video/*", use = "play" },
]

[plugin]
prepend_previewers = [
	{mime = "audio/*", run = "exifaudio"},
]
